### PR TITLE
ENT-11202, ENT-11335, ENT-11305: TOC bug-fixes

### PR DESCRIPTION
**Pull request by mineralsfree**
Ticket: ENT-11202 ENT-11335 ENT-11305
Changelog: None
Signed-off-by: Mikita Pilinka <mikita.pilinka@northern.tech>

### CODE REVIEW

**Comment by mineralsfree** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/527/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/527/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-527/output/_site/

**Review by olehermanse — APPROVED** [review]
Tested the preview, seems to work well

**Comment by olehermanse** [comment]
@mineralsfree remember to bring this to 3.21 and Alvaldi.

**Review by craigcomstock — COMMENTED** [review]
The changes look good to me but it seems like this could be split up into a few comments with explanations of what problem they fixed and how?

**Review by aleksandrychev — COMMENTED** [review]
lgtm

**Comment by mineralsfree** [comment]
Cherry-picked in #3227

**Comment by mineralsfree** [comment]
> The changes look good to me but it seems like this could be split up into a few comments with explanations of what problem they fixed and how?

I've updated the PR description. Will make better commit messages next time

**Pull request merged**
