### PR TITLE
ENT-11987: Clarify that cf-runagent --remote-bundles requires explicit bundle resource_type access promises

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-11987
Changelog: none

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins fast docs build please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/585/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/585/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-585/output/_site/

**Comment by craigcomstock** [comment]
rebuild after core changes in changelog that should fix problems here:

[Build Status](https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/591/)

**Review by nickanderson — APPROVED** [review]

**Comment by craigcomstock** [comment]
cherry pick to 3.21 https://github.com/cfengine/documentation/pull/3306

**Comment by craigcomstock** [comment]
picked to 3.24 https://github.com/cfengine/documentation/pull/3307

**Pull request merged**
