### PR TITLE
Do not process the `published: false` documents

### PR DESCRIPTION
**Pull request by aleksandrychev**
Ticket: ENT-10284

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/488/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/488/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-488/output/_site/

**Comment by aleksandrychev** [comment]
not published page on master  - https://docs.cfengine.com/docs/master/enterprise-cfengine-guide.html
on this build 404 - 
http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-488/output/_site/enterprise-cfengine-guide.html

**Review by olehermanse — APPROVED** [review]
ACK, thanks :)

**Pull request merged**
