### PR TITLE
ENT-8877: Replaced old image on the Health page (master)

### PR DESCRIPTION
**Pull request by chiachenglu**
Replaced old image on the [Health page.](https://docs.cfengine.com/docs/master/enterprise-cfengine-guide-health.html)

Ticket: ENT-8877 
Changelog: Replaced old image on the Health page

### CODE REVIEW

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8308/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8308/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8308/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-pr-pipeline-8308/output/_site/

**Comment by nickanderson** [comment]
Ah, i dont think craigs tom doc chagnes are merged yet, so its doing a slow build.

**Comment by nickanderson** [comment]
@cf-testtom jenkins please?

**Comment by chiachenglu** [comment]
I suppose it inevitably become so big because there is no style around it now. Please don't merge now, I will request the merges after [ENT-8493](https://tracker.mender.io/browse/ENT-8493) task been implemented. @nickanderson

**Pull request closed without merging**
