### PR TITLE
ENT-11371: Empty commit for triggering doc build with MPF changes

### PR DESCRIPTION
**Pull request by nickanderson**
Merge together:
- https://github.com/cfengine/masterfiles/pull/2835

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/94/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/94/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-94/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-94/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom try one more time in Jenkins, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/95/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/95/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-95/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-95/output/_site/

**Comment by olehermanse** [comment]
Failed, see: https://northerntech.atlassian.net/browse/ENT-10474

**Pull request closed without merging**
