### PR TITLE
More cleanups of capitalization, tabs, indentation, quoting

### PR DESCRIPTION
**Pull request by olehermanse**
- Replaced a few cases of `something' with `something`
- Replaced a few cases of `something' with _something_
- More backtick quote cleanups
- Cleaned up tabs and indentation
- Removed redundant table of contents
- Replaced non-ascii dash with regular dash
- Fixed capitalization of titles in additional topics
- Updated remaining titles to sentence case

### CODE REVIEW

**Comment by nickanderson** [comment]
@jenkins please

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/373/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/373/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-373/output/_site/

**Comment by nickanderson** [comment]
Backport to 3.21 https://github.com/cfengine/documentation/pull/3072

**Pull request merged**
