### PR TITLE
CFE-4131: Switched type() to use function attribute macro

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/282/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/282/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-282/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/283/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/283/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-283/output/_site/

**Pull request merged**
