### PR TITLE
Changed wrong command in developing modules (3.24)

### PR DESCRIPTION
**Pull request by victormlg**
Ticket: CFE-4457
Signed-off-by: Victor Moene <victor.moene@northern.tech>
(cherry picked from commit 406c16f6b7288398fcf5820f67162ac8452803b4)

### CODE REVIEW

**Review by olehermanse — APPROVED** [review]

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-3.24/29/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-3.24/29/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-3.24-29/output/_site/

**Review by craigcomstock — DISMISSED** [review]
s/developping/developing/ :) I already changed it in the PR title but please change in your commit as well.

Thanks!

**Comment by olehermanse** [comment]
> s/developping/developing/ :) I already changed it in the PR title but please change in your commit as well.

@craigcomstock this is a cherry-pick, too late to adjust the commit message in the original commit, I think it's okay / better to keep it as is here.

**Review by olehermanse — APPROVED** [review]
CI succeeded, preview looks good, merging.

**Pull request merged**
