### PR TITLE
Added TOC current items highlighting

### PR DESCRIPTION
**Pull request by aleksandrychev**
Ticket: ENT-9758

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/447/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/447/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-447/output/_site/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/449/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/449/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-449/output/_site/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/450/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/450/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-450/output/_site/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/451/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/451/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-451/output/_site/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/452/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/452/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-452/output/_site/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/453/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/453/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-453/output/_site/

**Comment by aleksandrychev** [comment]
@chiachenglu please review => http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-453/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/455/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/455/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-455/output/_site/

**Review by olehermanse — APPROVED** [review]
Looks great, thanks :)

**Comment by olehermanse** [comment]
Remember to bring over to Alvaldi docs.

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/464/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/464/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-464/output/_site/

**Comment by olehermanse** [comment]
@chiachenglu new preview link: http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-464/output/_site/

**Comment by chiachenglu** [comment]
@aleksandrychev Thanks for the work, 1 things I noticed seems not right in the [new preview link](http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-464/output/_site/), is the navigation table button doesn't react when I click on it (screen record 1)

https://github.com/cfengine/documentation/assets/82047138/1858ba7a-d5e8-441b-bc9c-dde7ace7aeb0

 not sure if it is because of the preview build is not configure right or other reason, please check :)

**Comment by aleksandrychev** [comment]
> @aleksandrychev Thanks for the work, 1 things I noticed seems not right in the [new preview link](http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-464/output/_site/), is the navigation table button doesn't react when I click on it (screen record 1)
> 
>  Screen.Recording.1.mov 
> not sure if it is because of the preview build is not configure right or other reason, please check :)

good catch! added change to preserve js functions names to the webpack

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins please

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/468/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/468/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-468/output/_site/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/470/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/470/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-470/output/_site/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/472/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/472/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-472/output/_site/

**Comment by chiachenglu** [comment]
I tried the latest [preview link](http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-472/output/_site/), the previous issue seems no longer exist, looks good to me! Thanks.

**Review by mineralsfree — APPROVED** [review]

**Comment by aleksandrychev** [comment]
@olehermanse please merge

alvaldi PR - https://github.com/NorthernTechHQ/alvaldi-docs/pull/96

**Pull request merged**
