### PR TITLE
Move documentation-generator into documentation repo

### PR DESCRIPTION
**Pull request by Lex-2008**
I did it using this one command:

    git subtree -P generator add ../documentation-generator master

plus two last commits.

To see how repo will look after the merge (incl history): https://github.com/Lex-2008/documentation

Ticket: ENT-8967

Merge together:
https://github.com/cfengine/documentation-generator/pull/335
lol, not really. Just need to update Jenkins to reference files in the new place.

### CODE REVIEW

**Review by cf-bottom — CHANGES_REQUESTED** [review]
Please use a company e-mail instead of l***@gmail.com,v***@mykolab.com

**Comment by Lex-2008** [comment]
green builds:
https://ci.cfengine.com/view/Documentation/job/fast-build-and-deploy-docs-master/160/
https://ci.cfengine.com/view/Documentation/job/build-and-deploy-docs-master/42/

**Review by nickanderson — APPROVED** [review]
I like that you preserved many commits. Is there a specific reason for not going ahead and preserving all commits? Personally, I prefer full history but I wont block merging this on that.

Also great that you went ahead and changed url references from generator.

**Comment by Lex-2008** [comment]
hmm, did i miss any commits? https://github.com/cfengine/documentation-generator claims to have 956 commits, this PR has 957...

**Comment by nickanderson** [comment]
Well, I looked at doc-generator 

> hmm, did i miss any commits? https://github.com/cfengine/documentation-generator claims to have 956 commits, this PR has 957...

Well, I looked at documentation-generator I find a bunch of commits before 2017 (the first commit I saw in this PR) https://github.com/cfengine/documentation-generator/commits/master?since=2008-01-01&until=2017-01-03

**Comment by Lex-2008** [comment]
Hmm, do you mean that if you open "commits" tab https://github.com/cfengine/documentation/pull/2852/commits
then github tells you that
> This pull request is big! We’re only showing the most recent 250 commits.

You can browse the original branch from this PR: https://github.com/Lex-2008/documentation/commits/master?since=2008-01-01&until=2017-01-03

**Comment by nickanderson** [comment]
Humm, weird, i see them in that pr branch, just strange to see that commits get newer scrolling down on the PR review

**Comment by nickanderson** [comment]
@Lex-2008 this was approved but still set as draft. I marked it ready for review so, lets merge this when it's working.

**Comment by Lex-2008** [comment]
thanks! also added commit(s) which was/were pushed while this PR was open, using this command:

    git subtree -P generator pull ../documentation-generator upstream/master

**Comment by Lex-2008** [comment]
FWIW,

> Approval not required
> This pull request may be merged without approvals. Learn more.

BUT

> Merging is blocked
> The base branch restricts merging to authorized users. Learn more about protected branches.

@nickanderson : can you please merge this?

**Pull request merged**
