### PR TITLE
ENT-11202: TOC scrolls with view

### PR DESCRIPTION
**Pull request by mineralsfree**
Ticket: ENT-11202
Changelog: None
Signed-off-by: Mikita Pilinka <mikita.pilinka@northern.tech>

### CODE REVIEW

**Comment by mineralsfree** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/514/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/514/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-514/output/_site/

**Comment by mineralsfree** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/515/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/515/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-515/output/_site/

**Comment by mineralsfree** [comment]
effects can be seen here: 
http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-516/output/_site/reference-components-cf-agent.html#control-promises

**Review by olehermanse — APPROVED** [review]

**Review by olehermanse — APPROVED** [review]

**Comment by aleksandrychev** [comment]
@mineralsfree good work 👍

@olehermanse don't we need scroll for TOC? otherwise I cannot scroll TOC and select hidden elements,  now I need to scroll the whole page

image

**Comment by olehermanse** [comment]
@aleksandrychev we discussed this during meeting yesterday. Yes scrolling could be nice, but could also be annoying (end up scrolling the wrong thing). This change is definitely required, a big improvement, and should be merged like this, at least for now.

**Comment by mineralsfree** [comment]
cherry-picked in #3215

**Pull request merged**
