### PR TITLE
Preview MPF doc change

### PR DESCRIPTION
**Pull request by nickanderson**
- Merge together:
- https://github.com/cfengine/masterfiles/pull/2888

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkinks please

**Comment by cf-bottom** [comment]
I'm not sure I understand, @nickanderson.

**Comment by nickanderson** [comment]
@cf-bottom build the docs in jenkins please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/107/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/107/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-107/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-107/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom build the docs in jenkins please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/108/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/108/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-108/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-108/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom build the docs in jenkins please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/109/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/109/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-109/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-109/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom build the docs in jenkins please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/110/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/110/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-110/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-110/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom build the docs in jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/111/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/111/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-111/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-111/output/_site/

**Pull request closed without merging**
