### PR TITLE
Adjusted styles

### PR DESCRIPTION
**Pull request by aleksandrychev**
Changed home page links weight

Fixed images view under li elements

Ticket: ENT-9537

ChangeLog: None

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkinx

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/245/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/245/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-245/output/_site/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/246/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/246/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-246/output/_site/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/247/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/247/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-247/output/_site/

**Review by olehermanse — APPROVED** [review]
Could have a more descriptive PR title / commit message, and maybe a picture or two to show off the changes, but looks good otherwise.

**Comment by aleksandrychev** [comment]
image

**Comment by aleksandrychev** [comment]
image

**Comment by aleksandrychev** [comment]
image

**Pull request merged**
