### PR TITLE
Fixed `Download all documentation` link

### PR DESCRIPTION
**Pull request by aleksandrychev**
Use branch version instead of the current master CFEnigne version

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom docs preview

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/187/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/187/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-187/output/_site/

**Comment by cf-bottom** [comment]
I'm not sure I understand, @aleksandrychev.

**Review by Lex-2008 — APPROVED** [review]

**Pull request merged**
