### PR TITLE
ENT-8866: Removed tags

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Review by larsewi — APPROVED** [review]
🚀

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/358/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/358/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-358/output/_site/

**Comment by olehermanse** [comment]
Backport:
https://github.com/cfengine/documentation/pull/3062

**Pull request merged**
