### PR TITLE
Fixed navigation on build previews

### PR DESCRIPTION
**Pull request by aleksandrychev**
Ticket: ENT-9107

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/189/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/189/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-189/output/_site/

**Review by Lex-2008 — APPROVED** [review]

**Comment by olehermanse** [comment]
@aleksandrychev Thanks! :)

**Pull request merged**
