### PR TITLE
Custom promise types: Fixed outdated examples and some syntax / formatting / highlighting (3.21)

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by olehermanse** [comment]
Cherry-picked one more commit from:
https://github.com/cfengine/documentation/pull/3245

**Comment by olehermanse** [comment]
@cf-bottom jenkins again, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-3.21/100/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-3.21/100/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-3.21-100/output/_site/

**Pull request merged**
