### PR TITLE
ENT-9402: Added note about ignore_interfaces.rx preferred location change

### PR DESCRIPTION
**Pull request by nickanderson**
Merge together:
- https://github.com/cfengine/core/pull/5357
- https://github.com/cfengine/masterfiles/pull/2750

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/396/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/396/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-396/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, again please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/397/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/397/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-397/output/_site/

**Review by larsewi — APPROVED** [review]
Thanks 🚀

**Pull request merged**
