### PR TITLE
ENT-11392: Custom promise type docs improvements

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/547/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/547/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-547/output/_site/

**Comment by olehermanse** [comment]
Thanks, please cherry-pick to 3.21

**Comment by nickanderson** [comment]
Picked https://github.com/cfengine/documentation/pull/3241

**Pull request merged**
