### PR TITLE
Wrap mustache_template_motd.cf with raw so that mustache will render

### PR DESCRIPTION
**Pull request by nickanderson**
- [x] https://docs.cfengine.com/docs/mustache/examples-example-snippets-promise-patterns-example_edit_motd.html

- [x] https://docs.cfengine.com/docs/master/examples-tutorials-render-files-with-mustache-templates.html
- [x] https://docs.cfengine.com/docs/master/examples-tutorials-manage-ntp.html

- [ ] https://docs.cfengine.com/docs/master/resources-faq-mustache-templating.html
  - Actually, this is simply an included example from core. https://github.com/cfengine/core/blob/558f212e9c6df679590b33d8718db3644b681459/examples/mustache_classes.cf#L40-L50

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/351/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/351/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-351/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/353/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/353/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-353/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/83/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/83/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-83/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-83/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/84/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/84/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-84/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-84/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/85/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/85/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-85/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-85/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/354/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/354/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-354/output/_site/

**Pull request merged**
