### PR TITLE
Docker fixups

### PR DESCRIPTION
**Pull request by nickanderson**
I tried the docker build and failed. These changes are my quick try for improvement.

- Tidied documentation for readability
- Added clone.sh script to make it easier to get the necessary repos
- Moved installation of execjs before redcarpet to avoid pulling it in with the wrong version as a dependency
```
Building native extensions.  This could take a while...
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for COPYING, skipping
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for COPYING, skipping
Successfully installed redcarpet-2.2.2
1 gem installed
Installing ri documentation for redcarpet-2.2.2...
Installing RDoc documentation for redcarpet-2.2.2...
ERROR:  Error installing uglifier:
        execjs requires Ruby version >= 2.5.0.
The command '/bin/sh -c bash -x /install.sh' returned a non-zero code: 1
```

### CODE REVIEW

**Comment by nickanderson** [comment]
Still not fully working. Running `main.sh` in the container fails:

```
export BRANCH=master
export PACKAGE_JOB=testing-pr
export PACKAGE_UPLOAD_DIRECTORY=jenkins-master-nightly-pipeline-1420
export PACKAGE_BUILD=1
docker run --rm -it -v $PWD:/nt docs bash -x documentation/generator/build/main.sh $BRANCH $PACKAGE_JOB $PACKAGE_UPLOAD_DIRECTORY $PACKAGE_BUILD
```

    -rw-r--r--  1 jenkins jenkins  833 Nov 22 15:56 rvm-installer.asc
    + source ~/.rvm/scripts/rvm
    documentation/generator/build/main.sh: line 117: -y: command not found

**Comment by nickanderson** [comment]
I modified main.sh swapping out references to ubuntu 18 with ubuntu 22 to match the dockerfile. I then rebuilt the docker container and I was then able to `docker run --rm -it -v $PWD:/nt docs bash -x documentation/generator/build/main.sh $BRANCH $PACKAGE_JOB $PACKAGE_UPLOAD_DIRECTORY $PACKAGE_BUILD`

**Comment by nickanderson** [comment]
I am then able to load the site in firefox from the local files. CSS and JS don't load because of wrong path issue.
I munged the html directly to use `./assets/footer-4bc00c8165fa8a0939d6661cb0bd6f02.js` instead of `./assets/footer-4bc00c8165fa8a0939d6661cb0bd6f02.js` and on refresh things look prettier.

**Review by craigcomstock — APPROVED** [review]
the changes look relatively harmless and if they improve the situation, cool.

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/421/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/421/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-421/output/_site/

**Comment by nickanderson** [comment]
Alrighty, this seems to work. So, merging.

**Pull request merged**
