### PR TITLE
Empty Commit for Doc build together with MPF change

### PR DESCRIPTION
**Pull request by nickanderson**
I want to get a doc preview with the big change to MPF.md from
https://github.com/cfengine/masterfiles/pull/2614

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/88/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/88/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-88/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-88/output/_site/

**Comment by nickanderson** [comment]
image
The links to the stdlib didn't work as expected, I tried removing the anchors.

@cf-bottom jenkins, again please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/89/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/89/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-89/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-89/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/90/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/90/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-90/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-90/output/_site/

**Pull request closed without merging**
