### PR TITLE
disable seccomp when building the docs container

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @nickanderson can review this?

**Comment by nickanderson** [comment]
@cf-bottom , Jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/209/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/209/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-209/output/_site/

**Comment by Lex-2008** [comment]
oslo-dc is back, no need for this pr anymore

**Pull request closed without merging**
