### PR TITLE
CFE-4095: Added cross references for function irange()

### PR DESCRIPTION
**Pull request by nickanderson**
Ticket: CFE-4095
Changelog: None

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/250/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/250/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-250/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/251/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/251/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-251/output/_site/

**Pull request merged**
