### PR TITLE
ENT-9964: Fixed capitalization of headings to be sentence case

### PR DESCRIPTION
**Pull request by olehermanse**
A lot of inconsistencies here as well. There's likely
more left, since it's a semi manual process, but it's
easier for me to do it in a few steps.

Found headings with multiple capital letters with bespoke
regexes, like this:

```
^##+ .*[A-Z].*[a-z].*[A-Z][a-z].*
```

I then put all the replacements in a text file and used a
python script to do the actual replacements, so I can replay
it in another branch.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom Jenkins, please :)

**Comment by olehermanse** [comment]
@cf-bottom Jenkins, please :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/333/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/333/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-333/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom Test again in Jenkins :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/334/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/334/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-334/output/_site/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/335/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/335/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-335/output/_site/

**Comment by nickanderson** [comment]
FAIL

**Comment by olehermanse** [comment]
@cf-bottom Test one more time in Jenkins, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/336/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/336/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-336/output/_site/

**Comment by nickanderson** [comment]
https://www.youtube.com/watch?v=FGBhQbmPwH8

**Comment by olehermanse** [comment]
Outdated, will replace with different PR.

**Pull request closed without merging**
