### PR TITLE
Moved build commands from main.sh to npm scripts

### PR DESCRIPTION
**Pull request by aleksandrychev**
this PR fixes missing search index

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/479/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/479/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-479/output/_site/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/480/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/480/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-480/output/_site/

**Review by mineralsfree — APPROVED** [review]

**Pull request merged**
