### PR TITLE
ENT-7742 Added MP and CFE_ROBOT credentials rotation docs

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-7742
Changelog: none

### CODE REVIEW

**Comment by craigcomstock** [comment]
Will keep as draft while I test on 3.15 and >3.15 systems.

**Comment by craigcomstock** [comment]
tested and fixed up on 3.15.5 and 3.18.1, should be good to go.

Eventually I think it would be a good idea to push these as real scripts in masterfiles to be used by policy to auto-rotate or rotate  on-demand.

**Comment by nickanderson** [comment]
What do you think about moving this content into https://github.com/cfengine/documentation/blob/master/enterprise-cfengine-guide/hub_administration/reset-admin-creds.markdown ?

**Comment by craigcomstock** [comment]
cherry picks
https://github.com/cfengine/documentation/pull/2608 (3.15)
https://github.com/cfengine/documentation/pull/2609 (3.18)

**Pull request merged**
