### PR TITLE
Centered docs for smaller than 951px width

### PR DESCRIPTION
**Pull request by aleksandrychev**
Ticket: ENT-9546

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/261/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/261/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-261/output/_site/

**Comment by olehermanse** [comment]
@aleksandrychev 
Screenshot 2022-11-30 at 13 33 37

I think at this breakpoint, the navigation button should be aligned together with the centered body

**Review by olehermanse — CHANGES_REQUESTED** [review]
See screenshot above.

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/262/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/262/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-262/output/_site/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/263/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/263/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-263/output/_site/

**Pull request merged**
