### PR TITLE
Attempt to set custom width for image

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom please build this in jenkins :)

**Comment by olehermanse** [comment]
@cf-bottom Please build one more time in Jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/66/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/66/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-66/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom Please build one more time in Jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/68/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/68/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-68/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom please build again now without raw.

**Comment by olehermanse** [comment]
@cf-bottom please build one final time.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/70/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/70/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-70/output/_site/

**Pull request merged**
