### PR TITLE
Make instructions for feeder uninstallation clearer

### PR DESCRIPTION
**Pull request by vpodzime**
And, in particular, make the last 'curl' invocation bold because
it's easy to miss.

Ticket: ENT-8851
Changelog: None

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom docs build in jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8119/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8119/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8119/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-pr-pipeline-8119/output/_site/

**Comment by vpodzime** [comment]
@cf-bottom another jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8120/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8120/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8120/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-pr-pipeline-8120/output/_site/

**Comment by vpodzime** [comment]
This is how it [looks now](http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-pr-pipeline-8120/output/_site/enterprise-cfengine-guide-federated-reporting.html#uninstall-with-the-api):
image

**Review by craigcomstock — APPROVED** [review]
yes, there are many ways to emphasize with language and structure. good improvement!

**Pull request merged**
