### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by btriller**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @nickanderson can review this?

**Review by nickanderson — APPROVED** [review]
Very good, thank you!

**Comment by nickanderson** [comment]
@cf-bottom can you build a preview in Jenkins please?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/255/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/255/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-255/output/_site/

**Pull request merged**
