### PR TITLE
ENT-9924: Added extra note about the importance of the MPF upgrade

### PR DESCRIPTION
**Pull request by nickanderson**
Ticket: ENT-9924
Changelog: None

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Review by craigcomstock — APPROVED** [review]
yeah, looks good! thanks!

**Comment by nickanderson** [comment]
Seems Tom is on holiday or something.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/316/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/316/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-316/output/_site/

**Pull request merged**
