### PR TITLE
Minor augments docs improvements

### PR DESCRIPTION
**Pull request by vpodzime**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @craigcomstock can review this?

**Comment by nickanderson** [comment]
@craigcomstock 
Maybe for version 4.0? :-P it's been the way it is for so long I think it would probably be bad to change it during 3.x

**Comment by nickanderson** [comment]
thanks @vpodzime !

**Comment by craigcomstock** [comment]
Yes @nickanderson I agree of course. It might be hard to change and keep backward compatibility. ;/

**Pull request merged**
