### PR TITLE
More cleanups of capitalization, table of contents, etc.

### PR DESCRIPTION
**Pull request by olehermanse**
- Normalized capitalization of changelog
- Removed duplicate table of contents
- Reformatted python files with black
- Changed more headings to be sentence case
- Removed non-ascii non-breaking space character

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/347/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/347/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-347/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom Once more in Jenkins :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/348/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/348/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-348/output/_site/

**Review by craigcomstock — APPROVED** [review]

**Pull request merged**
