### PR TITLE
Documentation restructuring with getting started

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/181/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/181/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-181/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom please build this in Jenkins again :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/182/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/182/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-182/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom please build this in Jenkins, one more time :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/191/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/191/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-191/output/_site/

**Pull request merged**
