### PR TITLE
Clarify JSON boolean handling and improve expression docs

### PR DESCRIPTION
**Pull request by tzz**
as requested by @jimis in https://github.com/cfengine/core/pull/2579

### CODE REVIEW

**Comment by jimis** [comment]
Looks good. Maybe also add a simple expression (i.e. no JSON) example? Maybe add it [here](https://docs.cfengine.com/docs/3.7/reference-promise-types-classes.html#expression) because I think that part is really empty, and the classes promise doc was the first one that came to my mind to look at. Or add a link toward the part you edited?

**Comment by tzz** [comment]
@nickanderson @jimis @kacf that reminds me, what do you think about `classes: "myclass" ==> "any"`?

In other words, can we add a syntactic shortcut for the equivalent but much more verbose `classes: "myclass" expression => "any"`? The exact syntax is not so important, as long as it's very short and doesn't require parser changes.

**Comment by nickanderson** [comment]
I'm not against it. But lets send this out to the community lists to see what others have to say.

**Comment by nickanderson** [comment]
After that perhaps bring it up in the #CAB

**Comment by tzz** [comment]
@nickanderson thank you for volunteering ;)

**Comment by tzz** [comment]
@jimis I added docs as you requested. Please feel free to fix them or amend them after merge.

**Comment by jimis** [comment]
> classes: "myclass" ==> "any"
I'm definitely **against**. No extra symbols, and this one specifically is rather confusing.

**Comment by jimis** [comment]
Thanks, merging.

**Comment by kacf** [comment]
>> classes: "myclass" ==> "any"
> 
> I'm definitely **against**. No extra symbols, and this one specifically is rather confusing.

I think I'm siding with Jimis on this one, it breaks with the whole language, and doesn't have a single keyword in it for recognition. Typing less is not always a good thing, as Perl has repeatedly shown (who thought `$|` or `$/` were good names?).

**Comment by tzz** [comment]
Hmm, I think shell and awk syntax was the model for Perl, you have things like `$@` etc.

I think at least the common `classes: "x" expression => "any"` can be shortened to `classes: "x"`.

**Comment by nickanderson** [comment]
I can get on board with classes: "any";

There is some precedence with methods: "method";

I also think that classes: "x" => "my.expression" is a decent candidate.

**Comment by jimis** [comment]
> I also think that classes: `"x" => "my.expression"` is a decent candidate.

It /looks/ fine, but I will side with @zzamboni's opinion on the mailing list. I vote against because it will complicate the only clear thing in our syntax. :-)

**Comment by zzamboni** [comment]
And just for reference, here is my comment from the mailing list:

> I’m not sure about this, and I think the reason is that I agree with Aleksey - one of the nice things of the CFEngine syntax is its regularity:
> 
> promise_type:
>    promiser
>       [ attribute => value … ]
> 
> The `attribute => value` pairs are optional - if we start making the `attribute` part optional, the syntax will get confusing (not to mention making the parsing more complicated). This is, if “expression” is optional for classes, what’s the default attribute for `vars`, for `files`, or for other promise types? While I can see the appeal in terms of shorter code, I fear it’s a slippery slope that could easily lead to confusing code:
> 
> files:
>    “/foo/bar” => og(“root”, “wheel”);   # “mode" by default?
> commands:
>   “/bin/foo” => “/etc”;      # “chdir” by default?
> etc.
> 
> I do like the part about `class: “foo”` being equivalent to `class: “foo” expression => “any”`, because it doesn’t break the syntax model.

**Comment by nickanderson** [comment]
Right, count me in that boat.
I don't personally have a burning desire to shorten "foo" => "expression". 

The "class"; shortening has precedence with reports type promises as well as the methods short-cut as of 3.7.

**Pull request merged**
