### PR TITLE
ENT-9118: Added monospace, sans-serif alternatives for pre elements (3.15)

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-9118
Changelog: none
(cherry picked from commit 906c63ac4b3ddaa594f5405be0c8d2709abba58f)

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom build yo

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-3.15/23/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-3.15/23/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-3.15-23/output/_site/

**Comment by craigcomstock** [comment]
Built documentation looks good to me. Merging. :)

**Review by aleksandrychev — COMMENTED** [review]
lgtm

**Pull request merged**
