### PR TITLE
Added `monospace`, `sans-serif` font family alternatives to pre tag (3.18)

### PR DESCRIPTION
**Pull request by aleksandrychev**

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins please

**Review by craigcomstock — APPROVED** [review]
love it

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-3.18/43/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-3.18/43/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-3.18-43/output/_site/

**Comment by craigcomstock** [comment]
maybe no quotes, I think chromium at least is looking for "Menlo, monospace, sans-serif" as a single font name with this one.

try this PR instead? https://github.com/cfengine/documentation/pull/2873

**Pull request closed without merging**
