### PR TITLE
ENT-11373: navigation tree collapse issue

### PR DESCRIPTION
**Pull request by mineralsfree**
Ticket: ENT-11373
Changelog: None
Signed-off-by: Mikita Pilinka <mikita.pilinka@northern.tech>

### CODE REVIEW

**Comment by mineralsfree** [comment]
@cf-bottom jenkins, pls

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/576/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/576/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-576/output/_site/

**Comment by mineralsfree** [comment]
cherry-picked #3280

**Review by olehermanse — APPROVED** [review]

**Comment by olehermanse** [comment]
@mineralsfree remember to also cherry-pick to alvaldi-docs

**Comment by mineralsfree** [comment]
"cherry-picked" to alvaldi-docs https://github.com/NorthernTechHQ/alvaldi-docs/pull/121

**Pull request merged**
