### PR TITLE
Fixed the last breadcrumbs item url

### PR DESCRIPTION
**Pull request by aleksandrychev**
Use alias instead of url

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/222/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/222/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-222/output/_site/

**Review by olehermanse — COMMENTED** [review]
👍

**Pull request merged**
