### PR TITLE
Added red hat text font

### PR DESCRIPTION
**Pull request by aleksandrychev**
Ticket: ENT-9193

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/226/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/226/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-226/output/_site/

**Review by olehermanse — APPROVED** [review]

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/228/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/228/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-228/output/_site/

**Review by chiachenglu — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
