### PR TITLE
ENT-4445: Document how hosts are deleted

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@craigcomstock @nickanderson @aleksandrychev please review.

**Comment by nickanderson** [comment]
@olehermanse Looks good. I will make a few minor modifications myself after merging.

This can be picked to 3.12.x, but since 3.10 includes redis, I guess not back to 3.10.x?

**Comment by olehermanse** [comment]
@nickanderson Actually, I think this is the same in 3.10. Only cross check needed is for the response codes, introduced recently by @aleksandrychev.

**Comment by nickanderson** [comment]
Picked to 3.12.x

**Comment by nickanderson** [comment]
@aleksandrychev are the return codes documented in this PR accurate for 3.10.x?

**Comment by nickanderson** [comment]
@aleksandrychev Never mind, it is: https://github.com/cfengine/nova/pull/1361

**Pull request merged**
