### PR TITLE
ENT-10286: Deleted outdated / empty documentation articles

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Review by larsewi — APPROVED** [review]
🚀

**Review by larsewi — APPROVED** [review]

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/361/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/361/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-361/output/_site/

**Comment by olehermanse** [comment]
Backports:
https://github.com/cfengine/documentation/pull/3059
https://github.com/cfengine/documentation/pull/3060

**Pull request merged**
