### PR TITLE
ENT-7928: Information architecture revamp

### PR DESCRIPTION
**Pull request by nickanderson**
Merge together:

- https://github.com/cfengine/documentation-generator/pull/311

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom can i haz a preview build?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/80/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/80/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-80/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom can i haz a preview build?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/81/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/81/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-81/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom can i haz a preview build, again, please?

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/82/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/82/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-82/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom can i haz jenkins build a preview, again, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/83/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/83/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-83/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom can I haz another preview build from jenkins?

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/84/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/84/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-84/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom can I haz another preview build from jenkins?

**Comment by nickanderson** [comment]
@craig here is one for your logic map. PRs that are only docs and doc-generator could be a fast build instead of slow, I suspect this will be slow.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/85/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/85/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-85/output/_site/

**Comment by nickanderson** [comment]
> @craigcomstock here is one for your logic map. PRs that are only docs and doc-generator could be a fast build instead of slow, I suspect this will be slow.

Nope, it was fast already :)

**Comment by nickanderson** [comment]
@cf-bottom can I haz another preview build from jenkins?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/86/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/86/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-86/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom can I haz another preview build from jenkins?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/87/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/87/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-87/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom can I haz another preview build from jenkins?

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/88/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/88/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-88/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom can I haz another preview build from jenkins?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/90/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/90/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-90/output/_site/

**Pull request merged**
