### PR TITLE
maxconnections

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
@nickanderson

**Comment by nickanderson** [comment]
Should we mention that the processes open file handles are controlled by this value as of ...?

**Comment by jimis** [comment]
These are internal details that might change if we see that the limit is hit again. I wouldn't document it but I can amend a small note if you insist.

**Comment by nickanderson** [comment]
I think it would be nice to have it noted somewhere, perhaps just a small history entry like

**History:** 3.10.1, 3.11.0, 3.7.6 automatic open file limits set

**Pull request merged**
