### PR TITLE
CFE-3926: Added documentation for copyfrom_admit_keys

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7594/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7594/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7594/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-pr-pipeline-7594/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Review by vpodzime — APPROVED** [review]
Looks good to me.

**Pull request merged**
