### PR TITLE
Add docs for the 'action_policy' custom module feature

### PR DESCRIPTION
**Pull request by vpodzime**
Ticket: CFE-3433
Changelog: None

Merge together:
https://github.com/cfengine/core/pull/5018
https://github.com/cfengine/documentation/pull/2842

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom build this in jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/155/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/155/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-155/output/_site/

**Comment by vpodzime** [comment]
> Sure, I triggered a build:
> 
> [Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/155/)
> 
> **Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/155/

No Ubuntu 18 HUB build from today's nightly because of:
```
09:05:55 dpkg: error: dpkg frontend is locked by another process
```

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/156/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/156/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-156/output/_site/

**Comment by vpodzime** [comment]
@cf-bottom now I want a slow build in jenkins, please

**Comment by olehermanse** [comment]
@cf-bottom can you try a normal build in jenkins now, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/41/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/41/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-41/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-41/output/_site/

**Review by nickanderson — APPROVED** [review]

**Review by olehermanse — APPROVED** [review]
Great, thanks! :)

**Comment by nickanderson** [comment]
@olehermanse backport to what branches (if any)?

**Comment by nickanderson** [comment]
I guess none, casue that's for 3.21 only.

**Pull request merged**
