### PR TITLE
Improve rendering on hierarchies page

### PR DESCRIPTION
**Pull request by Lex-2008**
* fix accidental code quotes
* remove code TOC at the end
* mark headers to be included in TOC

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build it to see how it looks

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/372/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/372/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-372/output/_site/

**Review by olehermanse — APPROVED** [review]
👍 🚀

**Comment by nickanderson** [comment]
This would not cherry pick cleanly.

https://github.com/cfengine/documentation/pull/3069

**Pull request merged**
