### PR TITLE
Update documentation to show template_data can take @(container)

### PR DESCRIPTION
**Pull request by tzz**
@nickanderson please double-check, thanks!

### CODE REVIEW

**Comment by atsaloli** [comment]
Thanks!

**Comment by kacf** [comment]
Thanks!

**Comment by kacf** [comment]
This is only valid for 3.9.0, right?

**Comment by tzz** [comment]
I think 3.8 and 3.7 as well, but am not sure.

**Comment by nickanderson** [comment]
You can't pass a data container directly in 3.7 I think.

t.cf
```
bundle agent main
{
    vars:
     "mycontainer" data => '[ 1, 2, 3 ]';

    files:
     "$(this.promise_filename).txt"
     create => "true",
     edit_template => "$(this.promise_filename).mustache",
     template_data => @(mycontainer),
     template_method => "mustache";
}
```

t.cf.mustache
```
{{%vars.main.mycontainer}};
```


Example Run
```
[root@hub vagrant]# cf-agent -V
CFEngine Core 3.7.2
CFEngine Enterprise 3.7.2
```

[root@hub vagrant]# cf-agent -KIf ./t.cf
    info: Updated rendering of '/vagrant/./t.cf.txt' from mustache template '/vagrant/./t.cf.mustache'
[root@hub vagrant]# cat t.cf.txt
;
[root@hub vagrant]#
```

But if you swtich the promise to mergedata()

```
bundle agent main
{
    vars:
     "mycontainer" data => '[ 1, 2, 3 ]';

    files:
     "$(this.promise_filename).txt"
     create => "true",
     edit_template => "$(this.promise_filename).mustache",
     template_data => mergedata(@(mycontainer)),
     template_method => "mustache";
}

```
```
[root@hub vagrant]# cf-agent -KIf ./t.cf
    info: Updated rendering of '/vagrant/./t.cf.txt' from mustache template '/vagrant/./t.cf.mustache'
[root@hub vagrant]# cat t.cf.txt
[
  1,
  2,
  3
];
[root@hub vagrant]# 
```

**Comment by tzz** [comment]
@nickanderson and 3.8? I think so, I recall making the change before 3.8 was released.

**Comment by nickanderson** [comment]
Just tested on 3.8 and same thing. 

Can *not* pass data container directly. So this needs to stay in master and it will be a good update for when 3.9 is released.

**Comment by tzz** [comment]
OK. Weird, I recalled it perfectly... sorry for the noise.

**Comment by kacf** [comment]
Thanks!

**Pull request merged**
