### PR TITLE
Fixed search page article max width

### PR DESCRIPTION
**Pull request by aleksandrychev**

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/265/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/265/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-265/output/_site/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/266/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/266/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-266/output/_site/

**Comment by olehermanse** [comment]
@aleksandrychev I am unsure what exactly changed here, and why, could you explain or provide before and after pictures?

**Comment by aleksandrychev** [comment]
before 
image

**Comment by aleksandrychev** [comment]
after 
image

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
