### PR TITLE
ENT-9757: Main navigation width adjustment (3.21)

### PR DESCRIPTION
**Pull request by mineralsfree**

### CODE REVIEW

**Comment by mineralsfree** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-3.21/62/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-3.21/62/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-3.21-62/output/_site/

**Comment by aleksandrychev** [comment]
comments are added to the master pr https://github.com/cfengine/documentation/pull/3131#pullrequestreview-1759813150

**Comment by mineralsfree** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-3.21/65/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-3.21/65/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-3.21-65/output/_site/

**Review by aleksandrychev — APPROVED** [review]

**Pull request merged**
