### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-testtom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/53/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/53/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-53/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-pr-pipeline-53/output/_site/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/54/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/54/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-fast-build-and-deploy-docs-master-54/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-54/output/_site/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/55/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/55/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-fast-build-and-deploy-docs-master-55/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-55/output/_site/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/56/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/56/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-56/output/_site/

**Comment by craigcomstock** [comment]
only for testing, so closing after cf-bottom learned how to build docs :)

**Pull request closed without merging**
