### PR TITLE
TEST: Some commits to see what breaks docs

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/136/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/136/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-136/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/138/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/138/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-138/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/139/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/139/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-139/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/140/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/140/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-140/output/_site/

**Comment by olehermanse** [comment]
Found that the commit which breaks it is the de-indenting code blocks commit. There is a bug in the generator:

https://github.com/cfengine/documentation-generator/pull/323

**Comment by olehermanse** [comment]
@cf-bottom Please build this in jenkins again, now that the bug has been fixed :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/146/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/146/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-146/output/_site/

**Comment by nickanderson** [comment]
@olehermanse you still need this?

**Comment by olehermanse** [comment]
@nickanderson nope

**Pull request closed without merging**
