### PR TITLE
CFE-4376: Empty commit to build docs and preview MPF change

### PR DESCRIPTION
**Pull request by nickanderson**
Merge together:
- https://github.com/cfengine/masterfiles/pull/2869

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/100/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/100/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-100/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-100/output/_site/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/101/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/101/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-101/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-101/output/_site/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/102/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/102/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-102/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-102/output/_site/

**Comment by nickanderson** [comment]
Link to relevant area in the last preview build (before squashing commits in MPF pr) http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-102/output/_site/reference-masterfiles-policy-framework-lib-files.html#set_user_field

**Pull request closed without merging**
