### PR TITLE
ENT-11977: Added the Audit logs API documentation

### PR DESCRIPTION
**Pull request by aleksandrychev**

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/623/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/623/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-623/output/_site/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/624/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/624/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-624/output/_site/

**Review by craigcomstock — APPROVED** [review]
yeah. cool! :ice_cube:

**Comment by aleksandrychev** [comment]
@craigcomstock please merge

**Pull request merged**
