### PR TITLE
Added links to articles sections

### PR DESCRIPTION
**Pull request by aleksandrychev**
Ticket: ENT-9103

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/198/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/198/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-198/output/_site/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/199/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/199/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-199/output/_site/

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
