### PR TITLE
Fixed broken links found by crawling with wget

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by nickanderson** [comment]
jenkins, please

**Comment by olehermanse** [comment]
These are the broken links I found with wget:

```
https://docs.cfengine.com/robots.txt
https://docs.cfengine.com/docs/master/cfengine-documentation-3.21.tar.gz
https://docs.cfengine.com/docs/master/putty-key-generator-window
https://docs.cfengine.com/docs/master/reference-enterprise-api-ref-inventory.html
https://docs.cfengine.com/docs/master/Funcions
https://docs.cfengine.com/docs/master/reference-standard-library-files.html
https://docs.cfengine.com/docs/master/lib/packages.cf
https://docs.cfengine.com/docs/master/reference-language-concepts-modules-package-modules.html
https://docs.cfengine.com/docs/master/read_module_protocol
https://docs.cfengine.com/docs/master/cf-hub
https://docs.cfengine.com/docs/master/%5BHost%20REST%20API
https://docs.cfengine.com/docs/master/bowtie-delegation.png
```

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/175/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/175/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-175/output/_site/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/176/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/176/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-176/output/_site/

**Review by Lex-2008 — APPROVED** [review]

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/177/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/177/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-177/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/178/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/178/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-178/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/179/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/179/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-179/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/180/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/180/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-180/output/_site/

**Pull request merged**
