### PR TITLE
Empty commit for triggering doc build with MPF changes

### PR DESCRIPTION
**Pull request by nickanderson**
Merge together:
- https://github.com/cfengine/masterfiles/pull/2839

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/96/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/96/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-96/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-96/output/_site/

**Comment by nickanderson** [comment]
Spurious? @cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/97/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/97/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-97/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-97/output/_site/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins, I fixed the job in jenkins to use the proper label: ubuntu-20 instead of 18. This build-and-deploy-docs-master job hasn't been used since Nov 2023 so rotted a bit. Now freshened up.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/build-and-deploy-docs-master/98/)

**Jenkins:** https://ci.cfengine.com/job/build-and-deploy-docs-master/98/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-build-and-deploy-docs-master-98/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-build-and-deploy-docs-master-98/output/_site/

**Pull request closed without merging**
