### PR TITLE
 ENT-10267: docs navigation doesn't show user's location

### PR DESCRIPTION
**Pull request by mineralsfree**
image

https://github.com/cfengine/documentation/assets/23060634/a946b89f-3f2c-4bc9-9ec4-1af37f91e5af

Ticket: ENT-10267
Changelog: None

### CODE REVIEW

**Comment by mineralsfree** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/435/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/435/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-435/output/_site/

**Comment by mineralsfree** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/436/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/436/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-436/output/_site/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/438/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/438/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-438/output/_site/

**Comment by mineralsfree** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/439/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/439/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-439/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/458/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/458/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-458/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/463/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/463/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-463/output/_site/

**Comment by olehermanse** [comment]
@mineralsfree In this case, i think a few sentences in the commit message about when it was not working before and how it was fixed could be helpful. Also, seeing before and after screenshots in the PR would be nice.

**Comment by olehermanse** [comment]
@mineralsfree I looked at the video and with your fix we are seeing the right navigation / context, but I also think we should add a highlight on the current article in the navigation.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/465/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/465/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-465/output/_site/

**Comment by mineralsfree** [comment]
@cf-bottom jenkins, please

**Comment by mineralsfree** [comment]
@cf-bottom jenkins, please

**Comment by mineralsfree** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/471/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/471/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-471/output/_site/

**Comment by mineralsfree** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/473/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/473/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-473/output/_site/

**Review by aleksandrychev — APPROVED** [review]

**Comment by craigcomstock** [comment]
@mineralsfree ah yeah, here I am checking commits for cherry picks for the release and found it a bit hard to find your cherry picks, but they are there and commited! 👍 I often make mention in the master PR of the cherry pick PRs, like:

cherry pick only to 3.21.x as 3.18.x does not have the modified navigation there

https://github.com/cfengine/documentation/pull/3170

**Comment by mineralsfree** [comment]
> @mineralsfree ah yeah, here I am checking commits for cherry picks for the release and found it a bit hard to find your cherry picks, but they are there and commited! 👍 I often make mention in the master PR of the cherry pick PRs, like:
> 
> cherry pick only to 3.21.x as 3.18.x does not have the modified navigation there
> 
> #3170

Thank you @craigcomstock, I'll do so next time

**Pull request merged**
