### PR TITLE
Editors: Added Zed and Pulsar, made VSCode, Zed, and Atom / Pulsar images links

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/619/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/619/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-619/output/_site/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/620/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/620/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-620/output/_site/

**Comment by olehermanse** [comment]
Failing GH action is fixed here:
https://github.com/cfengine/documentation/pull/3357

**Review by aleksandrychev — APPROVED** [review]

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/621/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/621/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-621/output/_site/

**Review by craigcomstock — APPROVED** [review]

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/622/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/622/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-622/output/_site/

**Review by nickanderson — APPROVED** [review]

**Comment by nickanderson** [comment]
backported to 3.24 and 3.21.

**Pull request merged**
