### PR TITLE
Updated legal link in footer

### PR DESCRIPTION
**Pull request by olehermanse**
Was working before due to redirect. Might as well go directly.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/512/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/512/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-512/output/_site/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/513/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/513/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-513/output/_site/

**Review by larsewi — APPROVED** [review]

**Comment by olehermanse** [comment]
Cherry-pick: https://github.com/cfengine/documentation/pull/3212

**Pull request merged**
