### PR TITLE
ENT-11156: Added shellcheck make target and github action workflow

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-11156
Changelog: none

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/485/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/485/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-485/output/_site/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/486/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/486/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-486/output/_site/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again, I fixed perms on oslo-dc that were broken probably due to a broken trap in the shell script not cleaning up afterwards.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/487/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/487/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-487/output/_site/

**Comment by craigcomstock** [comment]
@olehermanse @aleksandrychev the generated site from jenkins looks ok after poking around a dozen pages.
I made more changes to satisfy shellcheck but think this is probably solid. This is master so we can put it in right away and then cherry pick after our upcoming releases.

**Review by olehermanse — APPROVED** [review]
Thanks @craigcomstock, the changes look reasonable / safe.

**Comment by craigcomstock** [comment]
maybe cherry pick AFTER the release :+1:

**Comment by craigcomstock** [comment]
cherry picks, why not... we have the final tag now. :+1:

https://github.com/cfengine/documentation/pull/3195
https://github.com/cfengine/documentation/pull/3194

**Pull request merged**
