### PR TITLE
ENT-11202: TOC scrolls with view (3.21)

### PR DESCRIPTION
**Pull request by mineralsfree**
Ticket: ENT-11202
Changelog: None
Signed-off-by: Mikita Pilinka <mikita.pilinka@northern.tech>

(cherry picked from commit 32993a9cdd62b447c06f10695bf2b97fbc060761)

### CODE REVIEW

**Comment by mineralsfree** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-3.21/89/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-3.21/89/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-3.21-89/output/_site/

**Comment by olehermanse** [comment]
@mineralsfree scrolling is not working for me here: http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-3.21-89/output/_site/reference-masterfiles-policy-framework.html

**Comment by olehermanse** [comment]
Same on master - https://docs.cfengine.com/docs/master/reference-masterfiles-policy-framework.html

**Pull request merged**
