### PR TITLE
Various cleanups and consistency changes, including sentence case for headings

### PR DESCRIPTION
**Pull request by olehermanse**
- Made all titles use sentence case instead of title case
- Stripped unneccessary trailing # symbols in markdown headings
- Increased heading level of many headings within docs
- Fixed capitalization of headings to be sentence case
- More changes of title case to sentence case

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/323/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/323/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-323/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom jenkins again, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/324/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/324/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-324/output/_site/

**Comment by olehermanse** [comment]
@cf-bottom try Jenkins again?

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/326/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/326/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-326/output/_site/

**Comment by olehermanse** [comment]
2nd commit: https://github.com/cfengine/documentation/pull/3018

**Comment by olehermanse** [comment]
3rd commit: https://github.com/cfengine/documentation/pull/3019

**Comment by olehermanse** [comment]
@cf-bottom Please test this one again in Jenkins, I think I've found the issues.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/337/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/337/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-337/output/_site/

**Comment by olehermanse** [comment]
Outdated now, will put remaining parts in new PR.

**Pull request closed without merging**
