### PR TITLE
Added gifs and cf-remote save to getting started

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please?

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7570/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7570/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7570/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-pr-pipeline-7570/output/_site/

**Comment by nickanderson** [comment]
@Lex-2008 if we trigger the build from a PR to docs repo, can we skip `testing-pr (stable platforms)` ?

**Comment by Lex-2008** [comment]
No, because we need to compile a CFEngine hub in order to get a `cf-agent --help` output.

That's a job of testing-pr job now, and docs job builds only docs now.

**Comment by nickanderson** [comment]
Hum, would be nice if we could exclude all the builds we don't need.

**Comment by Lex-2008** [comment]
it will build only  "PACKAGES_HUB_x86_64_linux_ubuntu_16" (when a Jenkins slave is available).

**Pull request merged**
