### PR TITLE
Re-parent chmmon promise attributes

### PR DESCRIPTION
**Pull request by nickanderson**
This moves the reference documentation for attributes that are available to all
promise types to it's own page called `Common` at the same level as individual
promise type documents, but sorted to be listed first.

----

#

### CODE REVIEW

**Comment by craigcomstock** [comment]
Should we worry about old links to anchors like `https://docs.cfengine.com/docs/3.12/reference-promise-types.html#inherit_from` ?

**Comment by nickanderson** [comment]
I would only make this change in master and 3.15

**Comment by nickanderson** [comment]
But yes I need to search for links to these places first

**Comment by nickanderson** [comment]
I don't think this will happen for 3.15.0, recinding

**Pull request closed without merging**
