### PR TITLE
ENT-4299 Add missing SQL schema documentation

### PR DESCRIPTION
**Pull request by aleksandrychev**
ChangeLog: Title

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @nickanderson can review this?

**Comment by aleksandrychev** [comment]
@nickanderson  @craigcomstock, please review

**Comment by nickanderson** [comment]
What versions should this be cherry picked to?

**Comment by aleksandrychev** [comment]
@nickanderson  I think only 3.12.x

**Comment by nickanderson** [comment]
Can you make a PR to 3.12.x? It didn't pick cleanly

**Comment by aleksandrychev** [comment]
@nickanderson OK, before cherry-picking I will check 3.12 schema, probably they aren't equal

**Pull request merged**
