### PR TITLE
ENT-5866: Added documentation for edit.empty_before_use special variable

### PR DESCRIPTION
**Pull request by nickanderson**
Ticket: ENT-5866
Changelog: None

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/58/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/58/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-58/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/60/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/60/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-60/output/_site/

**Comment by craigcomstock** [comment]
@cf-testtom jenkins, please

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by craigcomstock** [comment]
@cf-bottom build please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/62/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/62/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-62/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/125/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/125/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-125/output/_site/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/fast-build-and-deploy-docs-master/128/)

**Jenkins:** https://ci.cfengine.com/job/fast-build-and-deploy-docs-master/128/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-128/output/_site/

**Pull request merged**
